var name = "Jochem Houtkoop.";
var level = "21.";
var xp = "297/365.";
var location = "Heemskerk.";
const companion = "True.";
var compdetails = "Name: Smib. Type: Cat.";
var money = "$99.999.999";
var lives = '1.';
const threat = 'high.';
const bounty = 'active';

console.log('Name: ' + name);
console.log('Level: ' + level);
console.log('XP: ' + xp);
console.log('Location: ' + location);
console.log('Companion: ' + companion);
console.log('Companion details: ' + compdetails);
console.log('Worth: ' + money);
console.log('Lives left: ' + lives);
console.log('Threat level: ' + threat);
console.log('Bounty: ' + bounty);